// flow-typed signature: 9bebff5efc4e7c9d0334cc310a0c93ea
// flow-typed version: <<STUB>>/lattice_v^0.32.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lattice/build/lattice' {
  declare module.exports: any;
}

declare module 'lattice/build/lattice.min' {
  declare module.exports: any;
}

declare module 'lattice/config/flow/types' {
  declare module.exports: any;
}

declare module 'lattice/config/jest/jest.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib/env.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib/lib.config' {
  declare module.exports: any;
}

declare module 'lattice/config/lib/paths.config' {
  declare module.exports: any;
}

declare module 'lattice/config/webpack/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'lattice/flow-typed/npm/axios_v0.17.x' {
  declare module.exports: any;
}

declare module 'lattice/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'lattice/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'lattice/flow-typed/npm/loglevel_v1.x.x' {
  declare module.exports: any;
}

declare module 'lattice/flow-typed/npm/moment_v2.3.x' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AnalysisApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AppApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AppApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AuthorizationApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/AuthorizationApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataSourcesApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/DataSourcesApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/EntityDataModelApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/EntityDataModelApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/LinkingApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/LinkingApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/OrganizationsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/OrganizationsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PermissionsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PermissionsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PrincipalsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/PrincipalsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/RequestsApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/RequestsApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SearchApi' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SearchApi.test' {
  declare module.exports: any;
}

declare module 'lattice/src/api/SyncApi' {
  declare module.exports: any;
}

declare module 'lattice/src/config/Configuration' {
  declare module.exports: any;
}

declare module 'lattice/src/config/Configuration.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiNames' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiNames.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiPaths' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/ApiPaths.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/ActionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/ActionTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/AnalyzerTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/index' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PermissionTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PermissionTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PrincipalTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/PrincipalTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/RequestStateTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/RequestStateTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/SecurableTypes' {
  declare module.exports: any;
}

declare module 'lattice/src/constants/types/SecurableTypes.test' {
  declare module.exports: any;
}

declare module 'lattice/src/index_default_export.test' {
  declare module.exports: any;
}

declare module 'lattice/src/index_named_export.test' {
  declare module.exports: any;
}

declare module 'lattice/src/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AccessCheck' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AccessCheck.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Ace' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Ace.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Acl' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Acl.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AclData' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AclData.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/AssociationType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/DataSource' {
  declare module.exports: any;
}

declare module 'lattice/src/models/DataSource.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntitySet.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/EntityType.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/FullyQualifiedName' {
  declare module.exports: any;
}

declare module 'lattice/src/models/FullyQualifiedName.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/index' {
  declare module.exports: any;
}

declare module 'lattice/src/models/index.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntitySet' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntitySet.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntityType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingEntityType.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingRequest' {
  declare module.exports: any;
}

declare module 'lattice/src/models/LinkingRequest.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Organization' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Organization.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Principal' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Principal.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/PropertyType' {
  declare module.exports: any;
}

declare module 'lattice/src/models/PropertyType.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Request' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Request.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/RequestStatus' {
  declare module.exports: any;
}

declare module 'lattice/src/models/RequestStatus.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Role' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Role.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Schema' {
  declare module.exports: any;
}

declare module 'lattice/src/models/Schema.test' {
  declare module.exports: any;
}

declare module 'lattice/src/models/template' {
  declare module.exports: any;
}

declare module 'lattice/src/models/template.test' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/getApiAxiosInstance' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/getApiAxiosInstance.test' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/getApiBaseUrl' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/getApiBaseUrl.test' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/index' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/newAxiosInstance' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/axios/newAxiosInstance.test' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/LangUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/Logger' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/testing/Invalid' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/testing/MockDataModels' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/testing/MockUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/testing/TestUtils' {
  declare module.exports: any;
}

declare module 'lattice/src/utils/ValidationUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lattice/build/lattice.js' {
  declare module.exports: $Exports<'lattice/build/lattice'>;
}
declare module 'lattice/build/lattice.min.js' {
  declare module.exports: $Exports<'lattice/build/lattice.min'>;
}
declare module 'lattice/config/flow/types.js' {
  declare module.exports: $Exports<'lattice/config/flow/types'>;
}
declare module 'lattice/config/jest/jest.config.js' {
  declare module.exports: $Exports<'lattice/config/jest/jest.config'>;
}
declare module 'lattice/config/lib/env.config.js' {
  declare module.exports: $Exports<'lattice/config/lib/env.config'>;
}
declare module 'lattice/config/lib/lib.config.js' {
  declare module.exports: $Exports<'lattice/config/lib/lib.config'>;
}
declare module 'lattice/config/lib/paths.config.js' {
  declare module.exports: $Exports<'lattice/config/lib/paths.config'>;
}
declare module 'lattice/config/webpack/webpack.config.babel.js' {
  declare module.exports: $Exports<'lattice/config/webpack/webpack.config.babel'>;
}
declare module 'lattice/flow-typed/npm/axios_v0.17.x.js' {
  declare module.exports: $Exports<'lattice/flow-typed/npm/axios_v0.17.x'>;
}
declare module 'lattice/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'lattice/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'lattice/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'lattice/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'lattice/flow-typed/npm/loglevel_v1.x.x.js' {
  declare module.exports: $Exports<'lattice/flow-typed/npm/loglevel_v1.x.x'>;
}
declare module 'lattice/flow-typed/npm/moment_v2.3.x.js' {
  declare module.exports: $Exports<'lattice/flow-typed/npm/moment_v2.3.x'>;
}
declare module 'lattice/src/api/AnalysisApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AnalysisApi'>;
}
declare module 'lattice/src/api/AppApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AppApi'>;
}
declare module 'lattice/src/api/AppApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/AppApi.test'>;
}
declare module 'lattice/src/api/AuthorizationApi.js' {
  declare module.exports: $Exports<'lattice/src/api/AuthorizationApi'>;
}
declare module 'lattice/src/api/AuthorizationApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/AuthorizationApi.test'>;
}
declare module 'lattice/src/api/DataApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataApi'>;
}
declare module 'lattice/src/api/DataApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/DataApi.test'>;
}
declare module 'lattice/src/api/DataSourcesApi.js' {
  declare module.exports: $Exports<'lattice/src/api/DataSourcesApi'>;
}
declare module 'lattice/src/api/DataSourcesApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/DataSourcesApi.test'>;
}
declare module 'lattice/src/api/EntityDataModelApi.js' {
  declare module.exports: $Exports<'lattice/src/api/EntityDataModelApi'>;
}
declare module 'lattice/src/api/EntityDataModelApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/EntityDataModelApi.test'>;
}
declare module 'lattice/src/api/LinkingApi.js' {
  declare module.exports: $Exports<'lattice/src/api/LinkingApi'>;
}
declare module 'lattice/src/api/LinkingApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/LinkingApi.test'>;
}
declare module 'lattice/src/api/OrganizationsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/OrganizationsApi'>;
}
declare module 'lattice/src/api/OrganizationsApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/OrganizationsApi.test'>;
}
declare module 'lattice/src/api/PermissionsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PermissionsApi'>;
}
declare module 'lattice/src/api/PermissionsApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/PermissionsApi.test'>;
}
declare module 'lattice/src/api/PrincipalsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/PrincipalsApi'>;
}
declare module 'lattice/src/api/PrincipalsApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/PrincipalsApi.test'>;
}
declare module 'lattice/src/api/RequestsApi.js' {
  declare module.exports: $Exports<'lattice/src/api/RequestsApi'>;
}
declare module 'lattice/src/api/RequestsApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/RequestsApi.test'>;
}
declare module 'lattice/src/api/SearchApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SearchApi'>;
}
declare module 'lattice/src/api/SearchApi.test.js' {
  declare module.exports: $Exports<'lattice/src/api/SearchApi.test'>;
}
declare module 'lattice/src/api/SyncApi.js' {
  declare module.exports: $Exports<'lattice/src/api/SyncApi'>;
}
declare module 'lattice/src/config/Configuration.js' {
  declare module.exports: $Exports<'lattice/src/config/Configuration'>;
}
declare module 'lattice/src/config/Configuration.test.js' {
  declare module.exports: $Exports<'lattice/src/config/Configuration.test'>;
}
declare module 'lattice/src/constants/ApiNames.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiNames'>;
}
declare module 'lattice/src/constants/ApiNames.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiNames.test'>;
}
declare module 'lattice/src/constants/ApiPaths.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiPaths'>;
}
declare module 'lattice/src/constants/ApiPaths.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/ApiPaths.test'>;
}
declare module 'lattice/src/constants/types/ActionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/ActionTypes'>;
}
declare module 'lattice/src/constants/types/ActionTypes.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/ActionTypes.test'>;
}
declare module 'lattice/src/constants/types/AnalyzerTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/AnalyzerTypes'>;
}
declare module 'lattice/src/constants/types/index.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/index'>;
}
declare module 'lattice/src/constants/types/PermissionTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PermissionTypes'>;
}
declare module 'lattice/src/constants/types/PermissionTypes.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PermissionTypes.test'>;
}
declare module 'lattice/src/constants/types/PrincipalTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PrincipalTypes'>;
}
declare module 'lattice/src/constants/types/PrincipalTypes.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/PrincipalTypes.test'>;
}
declare module 'lattice/src/constants/types/RequestStateTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/RequestStateTypes'>;
}
declare module 'lattice/src/constants/types/RequestStateTypes.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/RequestStateTypes.test'>;
}
declare module 'lattice/src/constants/types/SecurableTypes.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/SecurableTypes'>;
}
declare module 'lattice/src/constants/types/SecurableTypes.test.js' {
  declare module.exports: $Exports<'lattice/src/constants/types/SecurableTypes.test'>;
}
declare module 'lattice/src/index_default_export.test.js' {
  declare module.exports: $Exports<'lattice/src/index_default_export.test'>;
}
declare module 'lattice/src/index_named_export.test.js' {
  declare module.exports: $Exports<'lattice/src/index_named_export.test'>;
}
declare module 'lattice/src/index.js' {
  declare module.exports: $Exports<'lattice/src/index'>;
}
declare module 'lattice/src/models/AccessCheck.js' {
  declare module.exports: $Exports<'lattice/src/models/AccessCheck'>;
}
declare module 'lattice/src/models/AccessCheck.test.js' {
  declare module.exports: $Exports<'lattice/src/models/AccessCheck.test'>;
}
declare module 'lattice/src/models/Ace.js' {
  declare module.exports: $Exports<'lattice/src/models/Ace'>;
}
declare module 'lattice/src/models/Ace.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Ace.test'>;
}
declare module 'lattice/src/models/Acl.js' {
  declare module.exports: $Exports<'lattice/src/models/Acl'>;
}
declare module 'lattice/src/models/Acl.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Acl.test'>;
}
declare module 'lattice/src/models/AclData.js' {
  declare module.exports: $Exports<'lattice/src/models/AclData'>;
}
declare module 'lattice/src/models/AclData.test.js' {
  declare module.exports: $Exports<'lattice/src/models/AclData.test'>;
}
declare module 'lattice/src/models/AssociationType.js' {
  declare module.exports: $Exports<'lattice/src/models/AssociationType'>;
}
declare module 'lattice/src/models/DataSource.js' {
  declare module.exports: $Exports<'lattice/src/models/DataSource'>;
}
declare module 'lattice/src/models/DataSource.test.js' {
  declare module.exports: $Exports<'lattice/src/models/DataSource.test'>;
}
declare module 'lattice/src/models/EntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/EntitySet'>;
}
declare module 'lattice/src/models/EntitySet.test.js' {
  declare module.exports: $Exports<'lattice/src/models/EntitySet.test'>;
}
declare module 'lattice/src/models/EntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/EntityType'>;
}
declare module 'lattice/src/models/EntityType.test.js' {
  declare module.exports: $Exports<'lattice/src/models/EntityType.test'>;
}
declare module 'lattice/src/models/FullyQualifiedName.js' {
  declare module.exports: $Exports<'lattice/src/models/FullyQualifiedName'>;
}
declare module 'lattice/src/models/FullyQualifiedName.test.js' {
  declare module.exports: $Exports<'lattice/src/models/FullyQualifiedName.test'>;
}
declare module 'lattice/src/models/index.js' {
  declare module.exports: $Exports<'lattice/src/models/index'>;
}
declare module 'lattice/src/models/index.test.js' {
  declare module.exports: $Exports<'lattice/src/models/index.test'>;
}
declare module 'lattice/src/models/LinkingEntitySet.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntitySet'>;
}
declare module 'lattice/src/models/LinkingEntitySet.test.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntitySet.test'>;
}
declare module 'lattice/src/models/LinkingEntityType.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntityType'>;
}
declare module 'lattice/src/models/LinkingEntityType.test.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingEntityType.test'>;
}
declare module 'lattice/src/models/LinkingRequest.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingRequest'>;
}
declare module 'lattice/src/models/LinkingRequest.test.js' {
  declare module.exports: $Exports<'lattice/src/models/LinkingRequest.test'>;
}
declare module 'lattice/src/models/Organization.js' {
  declare module.exports: $Exports<'lattice/src/models/Organization'>;
}
declare module 'lattice/src/models/Organization.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Organization.test'>;
}
declare module 'lattice/src/models/Principal.js' {
  declare module.exports: $Exports<'lattice/src/models/Principal'>;
}
declare module 'lattice/src/models/Principal.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Principal.test'>;
}
declare module 'lattice/src/models/PropertyType.js' {
  declare module.exports: $Exports<'lattice/src/models/PropertyType'>;
}
declare module 'lattice/src/models/PropertyType.test.js' {
  declare module.exports: $Exports<'lattice/src/models/PropertyType.test'>;
}
declare module 'lattice/src/models/Request.js' {
  declare module.exports: $Exports<'lattice/src/models/Request'>;
}
declare module 'lattice/src/models/Request.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Request.test'>;
}
declare module 'lattice/src/models/RequestStatus.js' {
  declare module.exports: $Exports<'lattice/src/models/RequestStatus'>;
}
declare module 'lattice/src/models/RequestStatus.test.js' {
  declare module.exports: $Exports<'lattice/src/models/RequestStatus.test'>;
}
declare module 'lattice/src/models/Role.js' {
  declare module.exports: $Exports<'lattice/src/models/Role'>;
}
declare module 'lattice/src/models/Role.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Role.test'>;
}
declare module 'lattice/src/models/Schema.js' {
  declare module.exports: $Exports<'lattice/src/models/Schema'>;
}
declare module 'lattice/src/models/Schema.test.js' {
  declare module.exports: $Exports<'lattice/src/models/Schema.test'>;
}
declare module 'lattice/src/models/template.js' {
  declare module.exports: $Exports<'lattice/src/models/template'>;
}
declare module 'lattice/src/models/template.test.js' {
  declare module.exports: $Exports<'lattice/src/models/template.test'>;
}
declare module 'lattice/src/utils/axios/getApiAxiosInstance.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/getApiAxiosInstance'>;
}
declare module 'lattice/src/utils/axios/getApiAxiosInstance.test.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/getApiAxiosInstance.test'>;
}
declare module 'lattice/src/utils/axios/getApiBaseUrl.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/getApiBaseUrl'>;
}
declare module 'lattice/src/utils/axios/getApiBaseUrl.test.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/getApiBaseUrl.test'>;
}
declare module 'lattice/src/utils/axios/index.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/index'>;
}
declare module 'lattice/src/utils/axios/newAxiosInstance.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/newAxiosInstance'>;
}
declare module 'lattice/src/utils/axios/newAxiosInstance.test.js' {
  declare module.exports: $Exports<'lattice/src/utils/axios/newAxiosInstance.test'>;
}
declare module 'lattice/src/utils/LangUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/LangUtils'>;
}
declare module 'lattice/src/utils/Logger.js' {
  declare module.exports: $Exports<'lattice/src/utils/Logger'>;
}
declare module 'lattice/src/utils/testing/Invalid.js' {
  declare module.exports: $Exports<'lattice/src/utils/testing/Invalid'>;
}
declare module 'lattice/src/utils/testing/MockDataModels.js' {
  declare module.exports: $Exports<'lattice/src/utils/testing/MockDataModels'>;
}
declare module 'lattice/src/utils/testing/MockUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/testing/MockUtils'>;
}
declare module 'lattice/src/utils/testing/TestUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/testing/TestUtils'>;
}
declare module 'lattice/src/utils/ValidationUtils.js' {
  declare module.exports: $Exports<'lattice/src/utils/ValidationUtils'>;
}
