// flow-typed signature: 0bd08646a17a66cffd0b7cc62e371d53
// flow-typed version: <<STUB>>/react-reorder_v^2.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-reorder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-reorder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-reorder/examples/src/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-reorder/examples/src/js/index.js' {
  declare module.exports: $Exports<'react-reorder/examples/src/js/index'>;
}
declare module 'react-reorder/index' {
  declare module.exports: $Exports<'react-reorder'>;
}
declare module 'react-reorder/index.js' {
  declare module.exports: $Exports<'react-reorder'>;
}
