// flow-typed signature: b6bcf791576680afc18dbdfa2424108d
// flow-typed version: <<STUB>>/react-event-timeline_v^1.2.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-event-timeline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-event-timeline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-event-timeline/dist/index' {
  declare module.exports: any;
}

declare module 'react-event-timeline/dist/styles' {
  declare module.exports: any;
}

declare module 'react-event-timeline/dist/Timeline' {
  declare module.exports: any;
}

declare module 'react-event-timeline/dist/TimelineBlip' {
  declare module.exports: any;
}

declare module 'react-event-timeline/dist/TimelineEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-event-timeline/dist/index.js' {
  declare module.exports: $Exports<'react-event-timeline/dist/index'>;
}
declare module 'react-event-timeline/dist/styles.js' {
  declare module.exports: $Exports<'react-event-timeline/dist/styles'>;
}
declare module 'react-event-timeline/dist/Timeline.js' {
  declare module.exports: $Exports<'react-event-timeline/dist/Timeline'>;
}
declare module 'react-event-timeline/dist/TimelineBlip.js' {
  declare module.exports: $Exports<'react-event-timeline/dist/TimelineBlip'>;
}
declare module 'react-event-timeline/dist/TimelineEvent.js' {
  declare module.exports: $Exports<'react-event-timeline/dist/TimelineEvent'>;
}
