/*
 * @flow
 */

export const FETCH_ORG_REQUEST :string = 'FETCH_ORG_REQUEST';
export const FETCH_ORG_SUCCESS :string = 'FETCH_ORG_SUCCESS';
export const FETCH_ORG_FAILURE :string = 'FETCH_ORG_FAILURE';

export const FETCH_ORGS_REQUEST :string = 'FETCH_ORGS_REQUEST';
export const FETCH_ORGS_SUCCESS :string = 'FETCH_ORGS_SUCCESS';
export const FETCH_ORGS_FAILURE :string = 'FETCH_ORGS_FAILURE';

export const CREATE_NEW_ORG_REQUEST :string = 'CREATE_NEW_ORG_REQUEST';
export const CREATE_NEW_ORG_SUCCESS :string = 'CREATE_NEW_ORG_SUCCESS';
export const CREATE_NEW_ORG_FAILURE :string = 'CREATE_NEW_ORG_FAILURE';

export const JOIN_ORG_REQUEST :string = 'JOIN_ORG_REQUEST';
export const JOIN_ORG_SUCCESS :string = 'JOIN_ORG_SUCCESS';
export const JOIN_ORG_FAILURE :string = 'JOIN_ORG_FAILURE';

export const ADD_DOMAIN_TO_ORG_REQUEST :string = 'ADD_DOMAIN_TO_ORG_REQUEST';
export const ADD_DOMAIN_TO_ORG_SUCCESS :string = 'ADD_DOMAIN_TO_ORG_SUCCESS';
export const ADD_DOMAIN_TO_ORG_FAILURE :string = 'ADD_DOMAIN_TO_ORG_FAILURE';

export const REMOVE_DOMAIN_FROM_ORG_REQUEST :string = 'REMOVE_DOMAIN_FROM_ORG_REQUEST';
export const REMOVE_DOMAIN_FROM_ORG_SUCCESS :string = 'REMOVE_DOMAIN_FROM_ORG_SUCCESS';
export const REMOVE_DOMAIN_FROM_ORG_FAILURE :string = 'REMOVE_DOMAIN_FROM_ORG_FAILURE';

export const ADD_ROLE_TO_ORG_REQUEST :string = 'ADD_ROLE_TO_ORG_REQUEST';
export const ADD_ROLE_TO_ORG_SUCCESS :string = 'ADD_ROLE_TO_ORG_SUCCESS';
export const ADD_ROLE_TO_ORG_FAILURE :string = 'ADD_ROLE_TO_ORG_FAILURE';

export const REMOVE_ROLE_FROM_ORG_REQUEST :string = 'REMOVE_ROLE_FROM_ORG_REQUEST';
export const REMOVE_ROLE_FROM_ORG_SUCCESS :string = 'REMOVE_ROLE_FROM_ORG_SUCCESS';
export const REMOVE_ROLE_FROM_ORG_FAILURE :string = 'REMOVE_ROLE_FROM_ORG_FAILURE';
