/*
 * @flow
 */

export const FETCH_ORG_REQUEST :string = 'FETCH_ORG_REQUEST';
export const FETCH_ORG_SUCCESS :string = 'FETCH_ORG_SUCCESS';
export const FETCH_ORG_FAILURE :string = 'FETCH_ORG_FAILURE';

export const FETCH_ORGS_REQUEST :string = 'FETCH_ORGS_REQUEST';
export const FETCH_ORGS_SUCCESS :string = 'FETCH_ORGS_SUCCESS';
export const FETCH_ORGS_FAILURE :string = 'FETCH_ORGS_FAILURE';

export const FETCH_ORGS_AUTHORIZATIONS_REQUEST :string = 'FETCH_ORGS_AUTHORIZATIONS_REQUEST';
export const FETCH_ORGS_AUTHORIZATIONS_SUCCESS :string = 'FETCH_ORGS_AUTHORIZATIONS_SUCCESS';
export const FETCH_ORGS_AUTHORIZATIONS_FAILURE :string = 'FETCH_ORGS_AUTHORIZATIONS_FAILURE';

export const SEARCH_ORGS_REQUEST :string = 'SEARCH_ORGS_REQUEST';
export const SEARCH_ORGS_SUCCESS :string = 'SEARCH_ORGS_SUCCESS';
export const SEARCH_ORGS_FAILURE :string = 'SEARCH_ORGS_FAILURE';

export const JOIN_ORG_REQUEST :string = 'JOIN_ORG_REQUEST';
export const JOIN_ORG_SUCCESS :string = 'JOIN_ORG_SUCCESS';
export const JOIN_ORG_FAILURE :string = 'JOIN_ORG_FAILURE';
