/*
 * @flow
 */

export const CREATE_ORG_REQUEST :string = 'CREATE_ORG_REQUEST';
export const CREATE_ORG_SUCCESS :string = 'CREATE_ORG_SUCCESS';
export const CREATE_ORG_FAILURE :string = 'CREATE_ORG_FAILURE';

export const UPDATE_ORG_DESCRIPTION_REQUEST :string = 'UPDATE_ORG_DESCRIPTION_REQUEST';
export const UPDATE_ORG_DESCRIPTION_SUCCESS :string = 'UPDATE_ORG_DESCRIPTION_SUCCESS';
export const UPDATE_ORG_DESCRIPTION_FAILURE :string = 'UPDATE_ORG_DESCRIPTION_FAILURE';

export const UPDATE_ORG_TITLE_REQUEST :string = 'UPDATE_ORG_TITLE_REQUEST';
export const UPDATE_ORG_TITLE_SUCCESS :string = 'UPDATE_ORG_TITLE_SUCCESS';
export const UPDATE_ORG_TITLE_FAILURE :string = 'UPDATE_ORG_TITLE_FAILURE';
