/*
 * @flow
 */

export const FETCH_ALL_USERS_REQUEST :string = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS :string = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE :string = 'FETCH_ALL_USERS_FAILURE';
