/*
 * @flow
 */

export const FETCH_ALL_USERS_REQUEST :string = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS :string = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE :string = 'FETCH_ALL_USERS_FAILURE';

export const ADD_ROLE_TO_USER_REQUEST :string = 'ADD_ROLE_TO_USER_REQUEST';
export const ADD_ROLE_TO_USER_SUCCESS :string = 'ADD_ROLE_TO_USER_SUCCESS';
export const ADD_ROLE_TO_USER_FAILURE :string = 'ADD_ROLE_TO_USER_FAILURE';

export const REMOVE_ROLE_FROM_USER_REQUEST :string = 'REMOVE_ROLE_FROM_USER_REQUEST';
export const REMOVE_ROLE_FROM_USER_SUCCESS :string = 'REMOVE_ROLE_FROM_USER_SUCCESS';
export const REMOVE_ROLE_FROM_USER_FAILURE :string = 'REMOVE_ROLE_FROM_USER_FAILURE';
