/*
 * @flow
 */

export const FETCH_ALL_USERS_REQUEST :string = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS :string = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE :string = 'FETCH_ALL_USERS_FAILURE';

export const SET_USER_ROLES_REQUEST :string = 'SET_USER_ROLES_REQUEST';
export const SET_USER_ROLES_SUCCESS :string = 'SET_USER_ROLES_SUCCESS';
export const SET_USER_ROLES_FAILURE :string = 'SET_USER_ROLES_FAILURE';
