/*
 * @flow
 */

export const UPDATE_ASYNC_REFERENCE_OLD :string = 'UPDATE_ASYNC_REFERENCE_OLD';
export const UPDATE_ASYNC_REFERENCE :string = 'UPDATE_ASYNC_REFERENCE';
export const BULK_UPDATE_ASYNC_REFERENCE :string = 'BULK_UPDATE_ASYNC_REFERENCE';
export const RESOLVE_ASYNC_REFERENCE :string = 'RESOLVE_ASYNC_REFERENCE';

export default {
  UPDATE_ASYNC_REFERENCE_OLD,
  UPDATE_ASYNC_REFERENCE,
  BULK_UPDATE_ASYNC_REFERENCE
};
