export const UPDATE_ASYNC_REFERENCE = 'UPDATE_ASYNC_REFERENCE';
export const BULK_UPDATE_ASYNC_REFERENCE = 'BULK_UPDATE_ASYNC_REFERENCE';
export const RESOLVE_ASYNC_REFERENCE = 'RESOLVE_ASYNC_REFERENCE';

export default {
  UPDATE_ASYNC_REFERENCE,
  BULK_UPDATE_ASYNC_REFERENCE
};