/*
 * @flow
 */

export const RESOLVE_ASYNC_REFERENCE :string = 'RESOLVE_ASYNC_REFERENCE';
export const UPDATE_ASYNC_REFERENCE :string = 'UPDATE_ASYNC_REFERENCE';

export const UPDATE_ENTITY_SET_ASYNC_REFERENCES :string = 'UPDATE_ENTITY_SET_ASYNC_REFERENCES';
export const UPDATE_ENTITY_TYPE_ASYNC_REFERENCES :string = 'UPDATE_ENTITY_TYPE_ASYNC_REFERENCES';
export const UPDATE_PROPERTY_TYPE_ASYNC_REFERENCES :string = 'UPDATE_PROPERTY_TYPE_ASYNC_REFERENCES';
