export const ON_ASSOCIATION_SELECT = 'ON_TU_ASSOCIATION_SELECT';
export const ON_ARROW_SELECT = 'ON_TU_ARROW_SELECT';
export const ON_ENTITY_SELECT = 'ON_TU_ENTITY_SELECT';

export const SUBMIT_TOP_UTILIZERS_REQUEST = 'SUBMIT_TOP_UTILIZERS_REQUEST';
export const SUBMIT_TOP_UTILIZERS_SUCCESS = 'SUBMIT_TOP_UTILIZERS_SUCCESS';
export const SUBMIT_TOP_UTILIZERS_FAILURE = 'SUBMIT_TOP_UTILIZERS_FAILURE';
