export const ON_ENTITY_SELECT = 'ON_TU_ENTITY_SELECT';
export const SET_ENTITY_SETS = 'SET_TU_ENTITY_SETS';
export const SET_ENTITY_SET = 'SET_TU_ENTITY_SET';

export const GET_ENTITY_TYPES_REQUEST = 'GET_ENTITY_TYPES_REQUEST_TU';
export const GET_ENTITY_TYPES_SUCCESS = 'GET_ENTITY_TYPES_SUCCESS_TU';
export const GET_ENTITY_TYPES_FAILURE = 'GET_ENTITY_TYPES_FAILURE_TU';

export const SUBMIT_TOP_UTILIZERS_REQUEST = 'SUBMIT_TOP_UTILIZERS_REQUEST';
export const SUBMIT_TOP_UTILIZERS_SUCCESS = 'SUBMIT_TOP_UTILIZERS_SUCCESS';
export const SUBMIT_TOP_UTILIZERS_FAILURE = 'SUBMIT_TOP_UTILIZERS_FAILURE';
