/*
 * @flow
 */

export const ACL_KEY_PERMISSION_ADDED :string = 'ACL_KEY_PERMISSION_ADDED';
export const ACL_KEY_PERMISSION_REMOVED :string = 'ACL_KEY_PERMISSION_REMOVED';
export const ACL_KEY_PERMISSION_UPDATED :string = 'ACL_KEY_PERMISSION_UPDATED';

export const PERMISSION_REQUEST_APPROVED :string = 'PERMISSION_REQUEST_APPROVED';
export const PERMISSION_REQUEST_DECLINED :string = 'PERMISSION_REQUEST_DECLINED';
export const PERMISSION_REQUEST_SUBMITTED :string = 'PERMISSION_REQUEST_SUBMITTED';
