/*
 * @flow
 */

export const NEURON_CONNECT_REQUEST :string = 'NEURON_CONNECT_REQUEST';
export const NEURON_CONNECT_SUCCESS :string = 'NEURON_CONNECT_SUCCESS';
export const NEURON_CONNECT_FAILURE :string = 'NEURON_CONNECT_FAILURE';

export const NEURON_SUBSCRIBE_REQUEST :string = 'NEURON_SUBSCRIBE_REQUEST';
export const NEURON_SUBSCRIBE_SUCCESS :string = 'NEURON_SUBSCRIBE_SUCCESS';
export const NEURON_SUBSCRIBE_FAILURE :string = 'NEURON_SUBSCRIBE_FAILURE';

export const NEURON_ON_MESSAGE :string = 'NEURON_ON_MESSAGE';
export const NEURON_SIGNAL :string = 'NEURON_SIGNAL';
