/*
 * @flow
 */

export const LOAD_PRINCIPAL_DETAILS :string = 'LOAD_PRINCIPAL_DETAILS';

export const FETCH_ALL_USERS_REQUEST :string = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS :string = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE :string = 'FETCH_ALL_USERS_FAILURE';

export const FETCH_USERS_REQUEST :string = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS :string = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE :string = 'FETCH_USERS_FAILURE';

export const FETCH_USER_REQUEST :string = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS :string = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE :string = 'FETCH_USER_FAILURE';

export const SEARCH_ALL_USERS_BY_EMAIL_REQUEST :string = 'SEARCH_ALL_USERS_BY_EMAIL_REQUEST';
export const SEARCH_ALL_USERS_BY_EMAIL_SUCCESS :string = 'SEARCH_ALL_USERS_BY_EMAIL_SUCCESS';
export const SEARCH_ALL_USERS_BY_EMAIL_FAILURE :string = 'SEARCH_ALL_USERS_BY_EMAIL_FAILURE';
