export const LOAD_VISUALIZABLE_DATA_REQUEST :string = 'LOAD_VISUALIZABLE_DATA_REQUEST';
export const LOAD_VISUALIZABLE_DATA_SUCCESS :string = 'LOAD_VISUALIZABLE_DATA_SUCCESS';
export const LOAD_VISUALIZABLE_DATA_FAILURE :string = 'LOAD_VISUALIZABLE_DATA_FAILURE';

export const LOAD_ENTITY_SET_REQUEST :string = 'LOAD_ENTITY_SET_REQUEST';
export const LOAD_ENTITY_SET_SUCCESS :string = 'LOAD_ENTITY_SET_SUCCESS';
export const LOAD_ENTITY_SET_FAILURE :string = 'LOAD_ENTITY_SET_FAILURE';

export const LOAD_ENTITY_TYPE_REQUEST :string = 'LOAD_ENTITY_TYPE_REQUEST';
export const LOAD_ENTITY_TYPE_SUCCESS :string = 'LOAD_ENTITY_TYPE_SUCCESS';
export const LOAD_ENTITY_TYPE_FAILURE :string = 'LOAD_ENTITY_TYPE_FAILURE';

export const LOAD_PROPERTY_TYPES_REQUEST :string = 'LOAD_PROPERTY_TYPES_REQUEST';
export const LOAD_PROPERTY_TYPES_SUCCESS :string = 'LOAD_PROPERTY_TYPES_SUCCESS';
export const LOAD_PROPERTY_TYPES_FAILURE :string = 'LOAD_PROPERTY_TYPES_FAILURE';

export const CHECK_AUTHORIZATIONS_REQUEST :string = 'CHECK_AUTHORIZATIONS_REQUEST';
export const CHECK_AUTHORIZATIONS_SUCCESS :string = 'CHECK_AUTHORIZATIONS_SUCCESS';
export const CHECK_AUTHORIZATIONS_FAILURE :string = 'CHECK_AUTHORIZATIONS_FAILURE';

export const GET_DATA_REQUEST :string = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS :string = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE :string = 'GET_DATA_FAILURE';

export const GET_ALL_ENTITY_SETS_REQUEST :string = 'GET_ALL_ENTITY_SETS_REQUEST';
export const GET_ALL_ENTITY_SETS_SUCCESS :string = 'GET_ALL_ENTITY_SETS_SUCCESS';
export const GET_ALL_ENTITY_SETS_FAILURE :string = 'GET_ALL_ENTITY_SETS_FAILURE';

export const GET_ALL_ENTITY_TYPES_FOR_SETS_REQUEST :string = 'GET_ALL_ENTITY_TYPES_FOR_SETS_REQUEST';
export const GET_ALL_ENTITY_TYPES_FOR_SETS_SUCCESS :string = 'GET_ALL_ENTITY_TYPES_FOR_SETS_SUCCESS';
export const GET_ALL_ENTITY_TYPES_FOR_SETS_FAILURE :string = 'GET_ALL_ENTITY_TYPES_FOR_SETS_FAILURE';

export const GET_ALL_PROPERTY_TYPES_FOR_SETS_REQUEST :string = 'GET_ALL_PROPERTY_TYPES_FOR_SETS_REQUEST';
export const GET_ALL_PROPERTY_TYPES_FOR_SETS_SUCCESS :string = 'GET_ALL_PROPERTY_TYPES_FOR_SETS_SUCCESS';
export const GET_ALL_PROPERTY_TYPES_FOR_SETS_FAILURE :string = 'GET_ALL_PROPERTY_TYPES_FOR_SETS_FAILURE';

export const GET_VISUALIZABLE_ENTITY_SETS_REQUEST :string = 'GET_VISUALIZABLE_ENTITY_SETS_REQUEST';
export const GET_VISUALIZABLE_ENTITY_SETS_SUCCESS :string = 'GET_VISUALIZABLE_ENTITY_SETS_SUCCESS';
export const GET_VISUALIZABLE_ENTITY_SETS_FAILURE :string = 'GET_VISUALIZABLE_ENTITY_SETS_FAILURE';
