export const CATALOG_SEARCH_REQUEST = 'CATALOG_SEARCH_REQUEST';
export const CATALOG_SEARCH_REJECT = 'CATALOG_SEARCH_REJECT';
export const CATALOG_SEARCH_RESOLVE = 'CATALOG_SEARCH_RESOLVE';

export const ALL_ENTITY_SETS_REQUEST = 'ALL_ENTITY_SETS_REQUEST';
export const ALL_ENTITY_SETS_RESOLVE = 'ALL_ENTITY_SETS_RESOLVE';
export const ALL_ENTITY_SETS_REJECT = 'ALL_ENTITY_SETS_REJECT';
