export const ENTITY_SET_LIST_REQUEST = 'ENTITY_SET_LIST_REQUEST';
export const ENTITY_SET_LIST_FAILURE = 'ENTITY_SET_LIST_FAILURE';
export const ENTITY_SET_LIST_SUCCESS = 'ENTITY_SET_LIST_SUCCESS';

export const CATALOG_UPDATE_FILTER = 'CATALOG_UPDATE_FILTER';