/*
 * @flow
 */

export const CATALOG_SEARCH_REQUEST :string = 'CATALOG_SEARCH_REQUEST';
export const CATALOG_SEARCH_REJECT :string = 'CATALOG_SEARCH_REJECT';
export const CATALOG_SEARCH_RESOLVE :string = 'CATALOG_SEARCH_RESOLVE';
