export const CREATE_ENTITY_SET_REQUEST = 'CREATE_ENTITY_SET_REQUEST';
export const CREATE_ENTITY_SET_REJECT = 'CREATE_ENTITY_SET_REJECT';
export const CREATE_ENTITY_SET_RESOLVE = 'CREATE_ENTITY_SET_RESOLVE';
export const CREATE_ENTITY_SET_RESET = 'CREATE_ENTITY_SET_RESET';

export const CREATE_LINKED_ENTITY_SET_REQUEST :string = 'CREATE_LINKED_ENTITY_SET_REQUEST';
export const CREATE_LINKED_ENTITY_SET_RESOLVE :string = 'CREATE_LINKED_ENTITY_SET_RESOLVE';
export const CREATE_LINKED_ENTITY_SET_REJECT :string = 'CREATE_LINKED_ENTITY_SET_REJECT';
