export const CREATE_ENTITY_SET_REQUEST = 'CREATE_ENTITY_SET_REQUEST';
export const CREATE_ENTITY_SET_REJECT = 'CREATE_ENTITY_SET_REJECT';
export const CREATE_ENTITY_SET_RESOLVE = 'CREATE_ENTITY_SET_RESOLVE';