export const UPDATE_NORMALIZED_DATA = 'UPDATE_NORMALIZED_DATA';
export const FILTERED_EDM_REQUEST = 'FILTERED_EDM_REQUEST';
export const FILTERED_EDM_RESOLVE = 'FILTERED_EDM_RESOLVE';
export const FILTERED_EDM_REJECT = 'FILTERED_EDM_REJECT';

export const EDM_OBJECT_RESOLVE = 'edmObjectResolve';