export const UPDATE_NORMALIZED_DATA = 'UPDATE_NORMALIZED_DATA';
export const FILTERED_EDM_REQUEST = 'FILTERED_EDM_REQUEST';

export const EDM_OBJECT_RESOLVE = 'EDM_OBJECT_RESOLVE';

export const ALL_ENTITY_TYPES_REQUEST = 'ALL_ENTITY_TYPES_REQUEST';
export const ALL_ENTITY_TYPES_RESOLVE = 'ALL_ENTITY_TYPES_RESOLVE';
export const ALL_ENTITY_TYPES_REJECT = 'ALL_ENTITY_TYPES_REJECT';