/*
 * @flow
 */

export const FILTERED_EDM_REQUEST = 'FILTERED_EDM_REQUEST';

export const EDM_OBJECT_RESOLVE = 'EDM_OBJECT_RESOLVE';

export const ALL_ENTITY_TYPES_REQUEST = 'ALL_ENTITY_TYPES_REQUEST';
export const ALL_ENTITY_TYPES_RESOLVE = 'ALL_ENTITY_TYPES_RESOLVE';
export const ALL_ENTITY_TYPES_REJECT = 'ALL_ENTITY_TYPES_REJECT';

export const ALL_PROPERTY_TYPES_REQUEST = 'ALL_PROPERTY_TYPES_REQUEST';
export const ALL_PROPERTY_TYPES_RESOLVE = 'ALL_PROPERTY_TYPES_RESOLVE';
export const ALL_PROPERTY_TYPES_REJECT = 'ALL_PROPERTY_TYPES_REJECT';

export const UPDATE_ENTITY_SET_METADATA_REQUEST = 'UPDATE_ENTITY_SET_METADATA_REQUEST';
export const UPDATE_ENTITY_SET_METADATA_RESOLVE = 'UPDATE_ENTITY_SET_METADATA_RESOLVE';
export const UPDATE_ENTITY_SET_METADATA_REJECT = 'UPDATE_ENTITY_SET_METADATA_REJECT';

export const FETCH_ALL_ENTITY_SETS_REQUEST :string = 'FETCH_ALL_ENTITY_SETS_REQUEST';
export const FETCH_ALL_ENTITY_SETS_SUCCESS :string = 'FETCH_ALL_ENTITY_SETS_SUCCESS';
export const FETCH_ALL_ENTITY_SETS_FAILURE :string = 'FETCH_ALL_ENTITY_SETS_FAILURE';

export const FETCH_ALL_ENTITY_TYPES_REQUEST :string = 'FETCH_ALL_ENTITY_TYPES_REQUEST';
export const FETCH_ALL_ENTITY_TYPES_SUCCESS :string = 'FETCH_ALL_ENTITY_TYPES_SUCCESS';
export const FETCH_ALL_ENTITY_TYPES_FAILURE :string = 'FETCH_ALL_ENTITY_TYPES_FAILURE';

export const FETCH_ALL_PROPERTY_TYPES_REQUEST :string = 'FETCH_ALL_PROPERTY_TYPES_REQUEST';
export const FETCH_ALL_PROPERTY_TYPES_SUCCESS :string = 'FETCH_ALL_PROPERTY_TYPES_SUCCESS';
export const FETCH_ALL_PROPERTY_TYPES_FAILURE :string = 'FETCH_ALL_PROPERTY_TYPES_FAILURE';

export const FETCH_ENTITY_SET_PROJECTION_REQUEST :string = 'FETCH_ENTITY_SET_PROJECTION_REQUEST';
export const FETCH_ENTITY_SET_PROJECTION_SUCCESS :string = 'FETCH_ENTITY_SET_PROJECTION_SUCCESS';
export const FETCH_ENTITY_SET_PROJECTION_FAILURE :string = 'FETCH_ENTITY_SET_PROJECTION_FAILURE';

export const GET_ALL_ENTITY_SET_PROPERTY_METADATA_REQUEST :string = 'GET_ALL_ENTITY_SET_PROPERTY_METADATA_REQUEST';
export const GET_ALL_ENTITY_SET_PROPERTY_METADATA_SUCCESS :string = 'GET_ALL_ENTITY_SET_PROPERTY_METADATA_SUCCESS';
export const GET_ALL_ENTITY_SET_PROPERTY_METADATA_FAILURE :string = 'GET_ALL_ENTITY_SET_PROPERTY_METADATA_FAILURE';

export const UPDATE_ENTITY_SET_PROPERTY_METADATA_REQUEST :string = 'UPDATE_ENTITY_SET_PROPERTY_METADATA_REQUEST';
export const UPDATE_ENTITY_SET_PROPERTY_METADATA_SUCCESS :string = 'UPDATE_ENTITY_SET_PROPERTY_METADATA_SUCCESS';
export const UPDATE_ENTITY_SET_PROPERTY_METADATA_FAILURE :string = 'UPDATE_ENTITY_SET_PROPERTY_METADATA_FAILURE';

export const UPDATE_ENTITY_SETS :string = 'UPDATE_ENTITY_SETS';
