export const CHECK_AUTHORIZATION_REQUEST = 'CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_RESOLVE = 'CHECK_AUTHORIZATION_RESOLVE';
export const CHECK_AUTHORIZATION_REJECT = 'CHECK_AUTHORIZATION_REJECT';