/*
 * @flow
 */

export const CHECK_AUTHORIZATION_REQUEST :string = 'CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_RESOLVE :string = 'CHECK_AUTHORIZATION_RESOLVE';
export const CHECK_AUTHORIZATION_REJECT :string = 'CHECK_AUTHORIZATION_REJECT';

export const REQUEST_PERMISSIONS_MODAL_SHOW :string = 'REQUEST_PERMISSIONS_MODAL_SHOW';
export const REQUEST_PERMISSIONS_MODAL_HIDE :string = 'REQUEST_PERMISSIONS_MODAL_HIDE';