/*
 * @flow
 */

export const CHECK_AUTHORIZATION_REQUEST :string = 'CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_RESOLVE :string = 'CHECK_AUTHORIZATION_RESOLVE';
export const CHECK_AUTHORIZATION_REJECT :string = 'CHECK_AUTHORIZATION_REJECT';
