export const INITIAL_LOAD = 'INITIAL_LOAD';
export const LOAD_ENTITY_SET = 'LOAD_ENTITY_SET';
export const GET_ACLS = 'GET_ACLS';
export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS';
export const SET_ROLE_PERMISSIONS = 'SET_ROLE_PERMISSIONS';
export const SET_ENTITY_SET = 'SET_ENTITY_SET';
export const RESET_PERMISSIONS = 'RESET_PERMISSIONS';

export const GET_ALL_USERS_AND_ROLES_REQUEST = 'GET_ALL_USERS_AND_ROLES_REQUEST';
export const GET_ALL_USERS_AND_ROLES_SUCCESS = 'GET_ALL_USERS_AND_ROLES_SUCCESS';
export const GET_ALL_USERS_AND_ROLES_FAILURE = 'GET_ALL_USERS_AND_ROLES_FAILURE';

export const GET_USER_ROLE_PERMISSIONS_REQUEST = 'GET_USER_ROLE_PERMISSIONS_REQUEST';
export const GET_USER_ROLE_PERMISSIONS_SUCCESS = 'GET_USER_ROLE_PERMISSIONS_SUCCESS';
export const GET_USER_ROLE_PERMISSIONS_FAILURE = 'GET_USER_ROLE_PERMISSIONS_FAILURE';

export const GET_ALL_ORGANIZATIONS_REQUEST = 'GET_ALL_ORGANIZATIONS_REQUEST';
export const GET_ALL_ORGANIZATIONS_SUCCESS = 'GET_ALL_ORGANIZATIONS_SUCCESS';
export const GET_ALL_ORGANIZATIONS_FAILURE = 'GET_ALL_ORGANIZATIONS_FAILURE';
