export const ENTITY_SET_REQUEST = 'ENTITY_SET_REQUEST';
export const SET_ENTITY_DATA = 'SET_ENTITY_DATA';
export const SET_PROPERTY_DATA = 'SET_PROPERTY_DATA';
export const SET_ALL_USERS_AND_ROLES = 'SET_ALL_USERS_AND_ROLES';
export const SET_LOAD_USERS_ERROR = 'SET_LOAD_USERS_ERROR';
export const SET_NEW_ROLE_VALUE = 'SET_NEW_ROLE_VALUE';
