export const ENTITY_SET_REQUEST = 'ENTITY_SET_REQUEST';
export const SET_ENTITY_SET = 'ESDC_SET_ENTITY_SET';

export const GET_ENTITY_SET_SIZE_REQUEST = 'GET_ENTITY_SET_SIZE_REQUEST';
export const GET_ENTITY_SET_SIZE_SUCCESS = 'GET_ENTITY_SET_SIZE_SUCCESS';
export const GET_ENTITY_SET_SIZE_FAILURE = 'GET_ENTITY_SET_SIZE_FAILURE';
